name: build and push

on:
  push:
    branches: 
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # checkout the repository
    - name: checkout repository
      uses: actions/checkout@v1
    
    # setup dotnet cli
    - name: setup dotnet CLI
      uses: actions/setup-dotnet@v1.7.2
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-url: https://nuget.pkg.github.com/josepfranco/index.json
        owner: josepfranco
    
    # build the binaries
    - name: build with dotnet
      run: dotnet build --configuration Release
      shell: bash
    
    # pack the binaries into nuget
    - name: pack with dotnet
      run: dotnet pack --configuration Release --version-suffix 'ci-${{ github.run_number }}' --output './BUILDS/Release/' -NoDefaultExcludes
      shell: bash
    
    # publish to github packages nuget
    - name: publish to packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path: './BUILDS/Release/'
        repo-owner: 'josepfranco'
        gh-user: 'josepfranco'
        token: ${{ secrets.GITHUB_TOKEN }}
